### PR TITLE
Added link to analytics page from main landing page

### PR DESCRIPTION
**Pull request by chrism-bc**

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://yfthig-dev--pr-139-wtd600mw.web.app

**Review by Jxio — APPROVED** [review]

**Comment by tlebedovich** [comment]
@chrism-bc - can you please update the new link to be regular weight as per design instead of bold. thank you!

**Review by kialj876 — APPROVED** [review]

**Comment by chrism-bc** [comment]
https://github.com/bcgov/entity/issues/16693

**Pull request merged**
