### PR TITLE
BC Assessment, Site Registry, CSO - Dashboard and Landing Page

### PR DESCRIPTION
**Pull request by lekshmimallika-aot**
Issue: /bcgov/entity#13017, /bcgov/entity#13163, /bcgov/entity#13091

### CODE REVIEW

**Comment by lekshmimallika-aot** [comment]
The business is yet to confirm the URL for Learn more button.

**Review by kialj876 — APPROVED** [review]
Looks good to me 👍

**Comment by kialj876** [comment]
I think you'll need to ask Doug or Thor to add those new env variables in the deployment

**Comment by seeker25** [comment]
I'd recommend sending Fareen (OCM) some screenshots

**Review by doug-lovett — APPROVED** [review]

**Comment by doug-lovett** [comment]
Preview and gcb trigger env variables updated to add new ones:
BCA_URL = “[https://bcrosweb-dev.bcassessment.ca:54579/"](https://bcrosweb-dev.bcassessment.ca:54579/%22)
BCA_LEARN_MORE_URL = “”
ESRA_URL = “[https://esra-dlvr-frontend.apps.silver.devops.gov.bc.ca/"](https://esra-dlvr-frontend.apps.silver.devops.gov.bc.ca/%22)
ESRA_LEARN_MORE_URL = “[https://esra-prd-frontend.apps.silver.devops.gov.bc.ca/"](https://esra-prd-frontend.apps.silver.devops.gov.bc.ca/%22)
CSO_URL = “[https://dev.justice.gov.bc.ca/cso/index.do"](https://dev.justice.gov.bc.ca/cso/index.do%22)
CSO_LEARN_MORE_URL = “[https://justice.gov.bc.ca/cso/index.do"](https://justice.gov.bc.ca/cso/index.do%22)
Not sure why the check that builds the preview did not complete. The gcb console status for the build is green and completed at 4:01 PT yesterday.

**Comment by seeker25** [comment]
I think this PR is still missing the moved flags for the BC Online section..

I thought the whole point of having BC Assessment, Site registry, CSO joining the modernized application was to get off the old BC Online?

**Comment by tlebedovich** [comment]
> I think this PR is still missing the moved flags for the BC Online section.. (Similar to RPT and Wills)
> 
> I thought the whole point of having BC Assessment, Site registry, CSO joining the modernized application was to get off the old BC Online?
> 
> Correct me if I'm wrong
> 
> Example: https://github.com/seeker25/bcregistry/blob/f857e1ed68b3b2c69360d9ed270757657e7890d3/components/BCOnlineAccount.vue#L86

You are correct - as per the design tickets, on the BCROS landing page, each of the 3 products needs its BCOnLine tile updated with new text, "moved" tag and deactivated colours in addition the the "new" tiles added under BC Registries Account. @seeker25 @lekshmimallika-aot

**Comment by seeker25** [comment]
Thank you @tlebedovich

**Comment by lekshmimallika-aot** [comment]
> I think this PR is still missing the moved flags for the BC Online section.. (Similar to RPT and Wills)
> 
> I thought the whole point of having BC Assessment, Site registry, CSO joining the modernized application was to get off the old BC Online?
> 
> Correct me if I'm wrong
> 
> Example: https://github.com/seeker25/bcregistry/blob/f857e1ed68b3b2c69360d9ed270757657e7890d3/components/BCOnlineAccount.vue#L86

Made the changes to BCOnlineAccount component.

**Comment by seeker25** [comment]
sneak peak:

image

image

**Comment by seeker25** [comment]
Flags set to false:

image

image

**Pull request merged**
