### PR TITLE
Text updates to API gateway tile

### PR DESCRIPTION
**Pull request by orelbn**
*Issue #:* /bcgov/entity#17308

*Description of changes:*
- Updates text to remove reference to bc registers per updated design.

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://yfthig-dev--pr-144-p4suzmr3.web.app

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]
And me.

**Review by dimak1 — APPROVED** [review]

**Pull request merged**
