### PR TITLE
Update MHR tile image and text 

### PR DESCRIPTION
**Pull request by dimak1**
Issue #: https://github.com/bcgov/entity/issues/12240

Description:

- Update MHR tile Image and Description text

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]

**Comment by thorwolpert** [comment]
Temporary Url for review: https://yfthig-dev--pr-82-sxy3jpe8.web.app

**Comment by tlebedovich** [comment]
UXA - Text/image looks good for non-staff user. Does this PR include image/text on Staff dashboard as well?

**Comment by dimak1** [comment]
> UXA - Text/image looks good for non-staff user. Does this PR include image/text on Staff dashboard as well?

This task was to update tiles for Public User. I haven't done anything to Staff.

**Pull request merged**
