### PR TITLE
Update keycloak config.

### PR DESCRIPTION
**Pull request by doug-lovett**
Signed-off-by: Doug Lovett <doug@diamante.ca>

### CODE REVIEW

**Comment by doug-lovett** [comment]
Deployed to dev manually so no rush on this. Do we want to update the test and prod configs in this PR?

**Comment by pwei1018** [comment]
This PR should be closed. We don't need use the keycloak json anymore.

**Comment by doug-lovett** [comment]
Closing PR as deprecated.

**Pull request closed without merging**
