### PR TITLE
14028 Add orgbook.gov.bc.ca to the main page as a product

### PR DESCRIPTION
**Pull request by lewischenstudio**
Issue #: /https://github.com/bcgov/entity/issues/14028 

Description of changes:
- add orgbook.gov.bc.ca to the main page as a product

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcregistry license (Apache 2.0).

### CODE REVIEW

**Comment by lewischenstudio** [comment]
Hi @doug-lovett. Can you add the new build variable for the orgbok URL on the cloud build? Much obliged.

**Comment by doug-lovett** [comment]
GCP project id yfthig-dev cloud build triggers updated to add new substitution variable _ORGBOOK_URL.

**Review by doug-lovett — APPROVED** [review]
Looks good to me.

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Comment by lewischenstudio** [comment]
Thanks a lot for the approvals. @doug-lovett Can you merge the PR if everything looks fine? Thanks.

**Pull request merged**
